---
title: "OMI with Envirem data"
author: "Marit Kuijt"
date: "2023-02-14"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/marit/OneDrive/Documenten/Masterstage Naturalis/brassicaceae-trait-climate-analysis")
```

```{r}
library(geodata)
options(stringsAsFactors = FALSE)
library(raster)
library(tidyverse)
library(sp)
library(adehabitatMA)
library(optparse)
library(yaml)
library(dplyr)
library(ade4)
library(tibble)
library(logger)
library(CoordinateCleaner)
library(fuzzySim)
library(factoextra)
library(ggforce)
library(ggalt)
library(ggtree)
library(usdm)
library(subniche)
library(knitr)
library(phylolm)
library(ggnewscale)
library(ggplot2)
library(ggpubr)
```

```{r add_layers}
# Read Bioclim data and stack
remove(WorldENVIREM)
WorldENVIREM <- raster()

# The location of the TIFF file with the stacked layers described directly above
files.names <- list.files("./Data/ENVIREM")
# Turn the file names into layer names: strip the prefix (which might include
# the resolution) and strip the file extension
gis.layers.names <- files.names
gis.layers.names <- gsub('./Data/wc2.1_10m_','',gis.layers.names)
gis.layers.names <- gsub('.tif','',gis.layers.names)

gis.layers <- c()
# Iterate over files
for (j in 1:length(files.names)) {
  
  # Stack with previously read layers
  WorldENVIREM <- stack(
    WorldENVIREM,
    
    # Read as raster
    raster(
      
      # Construct file name
      paste("./Data/ENVIREM/", files.names[j], sep = "")
    )
  )
}

rm(gis.layers.names, files.names, j)
plot(WorldENVIREM)
```
```{r}
gis.layers.spdf <- as(WorldENVIREM, "SpatialPixelsDataFrame")
sp::proj4string(gis.layers.spdf) <- crs("+proj=longlat +ellps=WGS84", doCheckCRSArgs = T)
```

```{r}
occurrences.spdf <- new(
    "SpatialPointsDataFrame", 
    coords = structure(
        numeric(0), 
        .Dim = c(0L, 2L),
        .Dimnames = list( NULL, c("x", "y") )
    ),  
    bbox = structure(
        c(1,1,1,1), 
        .Dim = c(2L, 2L),                         
        .Dimnames = list( c("x","y"), c("min","max") )
    ),
    proj4string = crs("+proj=longlat +ellps=WGS84", doCheckCRSArgs = T)
) 
```

```{r}
# Populate the empty dataframe with lat/lon values from the taxa list
gbif_summary <- read.csv("Data/gbif_summary.csv")
# set for example i in 1:100 in the case of memory limits 
taxa.names <- gbif_summary[grep("Lepidium", gbif_summary$Name),]
taxa.names <- taxa.names$Name[taxa.names$BrassiBase_status == "accepted" & taxa.names$gbif_records_w_coordinates > 20]
for (j in 1:100) {
    
    # Prevent out of bounds errors
    if (j > length(taxa.names)) {
        break
    }
delayedAssign("do.next", {next})
  
	# Read occurrences
    species.key <- gbif_summary$speciesKey[gbif_summary$Name == taxa.names[j] & !duplicated(gbif_summary$Name)]
    csv.file <- paste("Data/gbif_occurrences_per_key/", species.key, ".csv", sep = "")
    csv.data <- read.csv(csv.file)
    #tryCatch(csv.data <- read.csv(csv.file), error=function(e) force(do.next))
    points.df <- dplyr::select(
        csv.data,
        decimalLongitude,
        decimalLatitude,
        species
    )
    points.df <- na.omit(points.df)
    tryCatch(cc_cap(points.df, lon = "decimalLongitude", lat = "decimalLatitude", species = "species"), error=function(e) force(do.next))
    tryCatch(cc_cen(points.df, lon = "decimalLongitude", lat = "decimalLatitude", species = "species"), error=function(e) force(do.next))
    tryCatch(cc_dupl(points.df, lon = "decimalLongitude", lat = "decimalLatitude", species = "species"), error=function(e) force(do.next))
    tryCatch(cc_equ(points.df, lon = "decimalLongitude", lat = "decimalLatitude"), error=function(e) force(do.next))
    tryCatch(cc_gbif(points.df, lon = "decimalLongitude", lat = "decimalLatitude", species = "species"), error=function(e) force(do.next))
    tryCatch(cc_inst(points.df, lon = "decimalLongitude", lat = "decimalLatitude", species = "species"), error=function(e) force(do.next))
    tryCatch(cc_outl(points.df, lon = "decimalLongitude", lat = "decimalLatitude", species = "species"), error=function(e) force(do.next))
    tryCatch(cc_sea(points.df, lon = "decimalLongitude", lat = "decimalLatitude"), error=function(e) force(do.next))
    tryCatch(cc_zero(points.df, lon = "decimalLongitude", lat = "decimalLatitude"), error=function(e) force(do.next))
    
    if(nrow(points.df) < 20) {next}
    sp::coordinates(points.df) <- ~ decimalLongitude + decimalLatitude
    proj4string(points.df) <- crs("+proj=longlat +ellps=WGS84", doCheckCRSArgs = T)
    
    # Populate SpatialPointsDataFrame for focal taxon
    focal.spdf <- SpatialPointsDataFrame(
    	points.df, 
    	data.frame(species = rep(taxa.names[j], NROW(points.df))), 
    	proj4string = crs("+proj=longlat +ellps=WGS84", doCheckCRSArgs = T)
    )
    proj4string(focal.spdf) <- crs("+proj=longlat +ellps=WGS84", doCheckCRSArgs = T)
    
    # Append to cumulative data frame
    occurrences.spdf <- rbind(occurrences.spdf, focal.spdf)
}
```

```{r}
names <- unique(occurrences.spdf$species)
```

```{r}
traitvalues.df <- slot(gis.layers.spdf, "data")
traitvalues.df <- tibble::rowid_to_column(traitvalues.df, "ID")
traitvalues.df <- na.omit(traitvalues.df)
```

```{r}
npoints <- adehabitatMA::count.points(occurrences.spdf, gis.layers.spdf)
noccurrences.df <- slot(npoints, "data")
noccurrences.df <- tibble::rowid_to_column(noccurrences.df, "ID")
noccurrences.df <- subset(noccurrences.df, noccurrences.df$ID %in% traitvalues.df$ID)
noccurrences.df <- subset(noccurrences.df, select = -ID)
noccurrences.df[noccurrences.df > 0] <- 1
```


#OMI analysis
##First a PCA
```{r}
traitvalues.dudi <- ade4::dudi.pca(
    traitvalues.df[2:length(traitvalues.df)], 
    scannf = F
)
```

##Then the OMI analysis
```{r}
niche.dudi <- ade4::niche(traitvalues.dudi, noccurrences.df, scannf = F)
scatter(niche.dudi)
screeplot(niche.dudi)
MeanBioClim <- niche.dudi$tab
```

```{r}
rbind(
  Eigenvalue = niche.dudi$eig,
  Proportion = niche.dudi$eig/sum(niche.dudi$eig),
  Cumulative = cumsum(niche.dudi$eig)/sum(niche.dudi$eig))
```

##Save output
```{r}
write.csv(niche.dudi$tab, file = "./Results/niche_traits_merged_Lepidium", append = T, quote = F )
```


#Read Tree and filter to Lepidium
```{r}
MetaData1 <- read_csv("./Data/2e.metadata.csv")
BrassiToL <- read.tree("Data/species_tree.tre")
names_to_drop <- setdiff(MetaData1$Name, names)
tips <- MetaData1$Library_ID[MetaData1$Name %in% names_to_drop]
BrassiToL_Lepidium <- drop.tip(BrassiToL, tips)
```

##Combine data
```{r}
Growth_Form_ID <- subset(MetaData1, Genus == "Lepidium", select = c(Library_ID, Growth_habit, Name))
Growth_Form <- data.frame(Growth_Form_ID)
rownames(Growth_Form) <- Growth_Form_ID$Library_ID
Growth_Form <- subset(Growth_Form, select = c(Growth_habit, Name))
```

```{r}
Growth_Form$Growth_habit[Growth_Form$Growth_habit == "H"] <- 0
Growth_Form$Growth_habit[Growth_Form$Growth_habit == "W"] <- 1
Growth_Form$Growth_habit <- base::as.numeric(Growth_Form$Growth_habit)
```

```{r}
rownames(MeanBioClim) <- gsub(".", " ", rownames(MeanBioClim), fixed = T)
common1 <- intersect(rownames(MeanBioClim), Growth_Form_ID$Name)
MeanBioClim <- MeanBioClim[common1,]
SpeciesNames <- rownames(MeanBioClim)
```

```{r}
common2 <- intersect(rownames(Growth_Form), BrassiToL_Lepidium$tip.label)
Growth_Form <- Growth_Form[common2,]
```

```{r}
for (i in 1:length(SpeciesNames)) {
  Growth_Form$annualPET[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_annualPET[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$aridityIndexThornthwaite[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_aridityIndexThornthwaite[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$climaticMoistureIndex[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_climaticMoistureIndex[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$continentality[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_continentality[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$embergerQ[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_embergerQ[rownames(MeanBioClim) == SpeciesNames[i]]
  Growth_Form$growingDegDays0[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_growingDegDays0[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$growingDegDays5[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_growingDegDays5[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$maxTempColdest[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_maxTempColdest[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$minTempWarmest[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_minTempWarmest[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$monthCountByTemp10[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_monthCountByTemp10[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$PETColdestQuarter[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_PETColdestQuarter[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$PETDriestQuarter[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_PETDriestQuarter[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$PETseasonality[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_PETseasonality[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$PETWarmestQuarter[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_PETWarmestQuarter[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$PETWettestQuarter[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_PETWettestQuarter[rownames(MeanBioClim) == SpeciesNames[i]]
  
  Growth_Form$thermicityIndex[Growth_Form$Name == SpeciesNames[i]] <- MeanBioClim$current_10arcmin_thermicityIndex[rownames(MeanBioClim) == SpeciesNames[i]]
}
```

```{r}
Growth_Form <- na.omit(Growth_Form)
```

```{r}
Growth_Form_Name <- subset(Growth_Form, select = Name)
Growth_Form_Trait <- subset(Growth_Form, select = Growth_habit)
  Growth_Form_Trait$Growth_habit <- as.factor(Growth_Form_Trait$Growth_habit)
Growth_Form_annualPET <- subset(Growth_Form, select = annualPET)
```


```{r}
p <- ggtree(BrassiToL_Lepidium, branch.length = "none") %<+% MetaData1 +
  geom_tiplab(size = 3) +
  geom_tiplab(aes(label = Name), offset = 2, size = 3)
p2 <- gheatmap(p, Growth_Form_Trait, offset = 5, width = 0.1)
p3 <- p2 + new_scale_fill()
gheatmap(p3, Growth_Form_annualPET, offset = 8, width = 0.1) + scale_fill_continuous(na.value = "white")

```

```{r}
Growth_Form$Growth_habit <- factor(Growth_Form$Growth_habit, levels = 0:1, labels = c(0,1))
```


```{r boxplots}


ggplot(Growth_Form, aes(Growth_habit, annualPET, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, PETColdestQuarter, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, PETWettestQuarter, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")
      
ggplot(Growth_Form, aes(Growth_habit, PETDriestQuarter, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, PETseasonality, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, PETWarmestQuarter, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, aridityIndexThornthwaite, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, climaticMoistureIndex, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, continentality, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, embergerQ, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, growingDegDays0, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, growingDegDays5, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, maxTempColdest, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, minTempWarmest, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, monthCountByTemp10, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

ggplot(Growth_Form, aes(Growth_habit, thermicityIndex, group = Growth_habit, fill = Growth_habit)) +
  geom_boxplot() +
  stat_compare_means(method = "t.test")

```


```{r}
MeanBioClim_small <- subset(MeanBioClim, select = c(current_10arcmin_annualPET, current_10arcmin_PETDriestQuarter, current_10arcmin_PETWarmestQuarter, current_10arcmin_aridityIndexThornthwaite, current_10arcmin_climaticMoistureIndex, current_10arcmin_growingDegDays0, current_10arcmin_growingDegDays5, current_10arcmin_minTempWarmest, current_10arcmin_monthCountByTemp10, current_10arcmin_thermicityIndex))
```

```{r}
vif(MeanBioClim_small[-c(3, 5, 6, 7, 8, 9)])
```


```{r}
unique(Growth_Form$Name)
formula_1 <- Growth_habit ~ annualPET + PETDriestQuarter + aridityIndexThornthwaite +  thermicityIndex #try to make a model to use in phyloglm, based on the boxplots and vif
```

```{r}
random <- runif(n = 88, min = 0, max = 2)
BrassiToL_Lepidium$edge.length <- random #until the cladogram is finished, some random brench lengths
```


```{r}
fit <- phyloglmstep(formula = formula_1, data = Growth_Form, phy = BrassiToL_Lepidium)
summary(fit)
```